"""Writes FINDINGS.md from the derived aggregate tables.

# TODO(nebius): route this analysis call through the gateway with
# tier="ultra" (nvidia/nemotron-3-ultra-*) once real Nemotron Ultra access is
# confirmed, so the findings report is genuinely model-written from the
# aggregate data. For now this runs against MockModelBackend so `agentdyno
# report` produces a real FINDINGS.md today.
"""
from __future__ import annotations

import json
from pathlib import Path

import httpx

from agentdyno.profiler.derive import derive

REPO_ROOT = Path(__file__).resolve().parents[2]
GATEWAY_URL = "http://127.0.0.1:8000/v1/chat/completions"


def _summarize_via_gateway(agg_records: list[dict], frontier: list[dict], gateway_url: str) -> str:
    prompt = (
        "You are writing a short findings report for an experiment comparing "
        "coding-agent harness architectures on task success vs inference cost.\n"
        f"Per-architecture aggregates: {json.dumps(agg_records, default=str)}\n"
        f"Pareto frontier: {json.dumps(frontier, default=str)}\n"
        "Write 2-4 sentences summarizing the key tradeoff."
    )
    payload = {
        "model": "nvidia/nemotron-3-ultra-253b",
        "messages": [{"role": "user", "content": prompt}],
        "tier": "ultra",
        "role": "analysis",
        "stream": True,
    }
    text = ""
    try:
        with httpx.stream("POST", gateway_url, json=payload, timeout=30.0) as resp:
            for line in resp.iter_lines():
                if not line or not line.startswith("data: "):
                    continue
                data = line[len("data: "):]
                if data == "[DONE]":
                    break
                chunk = json.loads(data)
                delta = chunk.get("choices", [{}])[0].get("delta", {}).get("content")
                if delta:
                    text += delta
    except httpx.HTTPError as e:
        return f"(gateway unreachable while generating narrative: {e})"
    return text.strip()


def write_findings(gateway_url: str = GATEWAY_URL, output_path: Path | None = None) -> Path:
    result = derive()
    agg = result["per_architecture"]
    frontier = result["pareto_frontier"]

    agg_records = agg.to_dict("records")
    narrative = _summarize_via_gateway(agg_records, frontier, gateway_url)

    lines = [
        "# FINDINGS",
        "",
        "> Generated by `agentdyno report`. The narrative below is produced by "
        "MockModelBackend acting as a stand-in for Nemotron Ultra - real Nemotron "
        "Ultra access is pending Nebius Token Factory credentials (# TODO(nebius)).",
        "",
        "## Narrative",
        "",
        narrative or "(no data yet - run `agentdyno run experiments/mvp.yaml` first)",
        "",
        "## Per-architecture aggregates",
        "",
        "| architecture | tier | trials | success_rate | ttft_mean_s | itl_p99_s | cost_per_solved_task |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in agg_records:
        lines.append(
            f"| {r['architecture']} | {r['tier']} | {r['n_trials']} | "
            f"{r['success_rate']:.2f} | {r['ttft_mean_s']:.3f} | {r['itl_p99_s']:.3f} | "
            f"{r['cost_per_solved_task']:.6f} |"
        )

    lines += ["", "## Pareto frontier (success vs cost)", ""]
    for r in frontier:
        lines.append(
            f"- **{r['architecture']} / {r['tier']}**: success_rate={r['success_rate']:.2f}, "
            f"cost_per_solved_task=${r['cost_per_solved_task']:.6f}"
        )

    out = output_path or (REPO_ROOT / "FINDINGS.md")
    out.write_text("\n".join(lines) + "\n")
    return out
